import { ITEMS, SKILLS, SHOP_TOMES, type ItemId, type ItemSpec, type ItemSlot } from '../game/config';
import type { Player } from '../game/types';
const itemIds = Object.keys(ITEMS) as ItemId[];
export function heroProgressionPanel() {
  return `<h2>Hero progression</h2><p id="hero-progress"></p><progress id="xp-bar"></progress><p id="hero-details"></p><div class="buttons"><button data-style="melee">Melee · close combat</button><button data-style="ranged">Ranged · bow</button><button data-panel="items">Equipment & items</button></div><h2>Training</h2>${(['warfare', 'vitality', 'command'] as const).map(kind => `<button data-training="${kind}"></button><small id="training-${kind}"></small>`).join('')}<p>Warfare: +15 melee / +5 ranged per rank. Vitality: +250 HP. Command: +5% nearby army damage per rank.</p><h2>Skills</h2><p id="skill-points"></p><details><summary>Ability hotkeys</summary><div id="ability-bindings"></div></details>${['Command', 'Warfare', 'Endurance', 'Ultimate'].map(branch => `<div class="skill-branch"><h3>${branch}</h3>${Object.entries(SKILLS).filter(([, spec]) => spec.branch === branch).map(([id, spec]) => `<div class="skill"><button data-skill="${id}"></button><small>${spec.description}</small><small id="skill-reason-${id}"></small></div>`).join('')}</div>`).join('')}`;
}
export function equipmentPanel(p: Player) {
  const slots: ItemSlot[] = ['melee', 'ranged', 'armor', 'boots', 'charm'];
  return `<h2>Equipped on hero</h2><p id="hero-details"></p>${slots.map(slot => { const id = p.equipment[slot]; return `<div class="equipped-slot"><strong>${slot}</strong><span>${id ? ITEMS[id].name : 'Empty'}</span>${id ? `<small>${ITEMS[id].description}</small><button data-unequip="${slot}">Unequip</button>` : ''}</div>`; }).join('')}<h2>Inventory</h2>${itemIds.filter(id => p.items[id]).map(id => `<div class="item-card"><strong>${ITEMS[id].name}</strong><small>${ITEMS[id].description}</small><button data-equip="${id}" ${p.equipment[ITEMS[id].slot] === id ? 'disabled' : ''}>${p.equipment[ITEMS[id].slot] === id ? 'Equipped' : `Equip ${ITEMS[id].slot}`}</button></div>`).join('') || '<p>Craft gear at the workshop or buy it from the merchant.</p>'}<button data-select="crafting">Open workshop</button>`;
}
export function workshopPanel() {
  return `<h2>Workshop recipes</h2><p id="items-status"></p>${itemIds.filter(id => 'cost' in ITEMS[id]).map(id => { const s: ItemSpec = ITEMS[id], c = s.cost!; return `<div class="item-card"><strong>${s.name}</strong><small>${s.description}</small><small>Workshop ${s.tier} · ${c.gold}g / ${c.wood}w / ${c.ore}o · ${s.craftTime}s</small><button data-craft="${id}">Craft</button><small id="craft-reason-${id}"></small></div>`; }).join('')}<button data-panel="items">View hero equipment</button>`;
}
export function merchantPanel(p: Player) {
  return `<h2>Merchant</h2><p id="merchant-status"></p><button data-action="travel-merchant">Send hero to merchant</button><p>Buy and sell with your living hero inside the safe circle. Legendary gear fills one equipment slot; tomes permanently grant extra abilities.</p><div class="buttons"><button data-consumable="healing">Healing · 90g</button><button data-consumable="mana">Mana draught · 120g</button></div>${Object.entries(SHOP_TOMES).map(([id, s]) => `<div class="item-card"><strong>${s.name}</strong><small>Unlock ${id === 'warcry' ? 'nearby army damage buff' : 'nearby army protection'} at rank I, without a normal skill slot.</small><button data-consumable="${id}">${s.buy} gold</button></div>`).join('')}${itemIds.map(id => `<div class="item-card"><strong>${ITEMS[id].name}</strong><small>${ITEMS[id].description}</small><button data-buy-item="${id}">${p.items[id] ? 'Owned' : `Buy · ${ITEMS[id].buy}g`}</button>${p.items[id] ? `<button data-sell-item="${id}">Sell · ${ITEMS[id].sell}g</button>` : ''}</div>`).join('')}`;
}
